#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
wrapper="${repo_root}/tools/au250_qwen35_run.sh"
builder="${repo_root}/tools/build_au250_qwen35_runtime.sh"
cublas_shim="${repo_root}/zluda/src/cublas_shim.c"

test -x "${wrapper}"
test -x "${builder}"
bash -n "${wrapper}"
bash -n "${builder}"
grep -Fq '#define _GNU_SOURCE' "${cublas_shim}"

grep -Fq 'AU250_QWEN_MODEL_ROOT:-/root/models/qwen35-tq1' "${wrapper}"
grep -Fq 'AU250_QWEN_LLAMA_ROOT:-/tmp/llama.cpp-qwen-context' "${wrapper}"
grep -Fq 'AU250_CUDA_ROOT:-/usr/local/cuda-13.0' "${wrapper}"
grep -Fq -- '--git-common-dir' "${wrapper}"
grep -Fq -- '-v "${git_common_dir}":"${git_common_dir}":ro' "${wrapper}"
grep -Fq '_au250_devflags' "${wrapper}"
grep -Fq '_au250_fpga_temp' "${wrapper}"
grep -Fq '/models/qwen:ro' "${wrapper}"
grep -Fq '/llama-pristine:ro' "${wrapper}"
grep -Fq '/usr/local/cuda-13.0:ro' "${wrapper}"
grep -Fq 'cuda-compat' "${wrapper}"
grep -Fq 'cuda_compat_math_header' "${wrapper}"
grep -Fq '/usr/local/cuda-13.0/targets/x86_64-linux/include/crt/math_functions.h:ro' "${wrapper}"
grep -Fq 'double rsqrt(double a) noexcept(true)' "${wrapper}"
grep -Fq 'float rsqrtf(float a) noexcept(true)' "${wrapper}"
grep -Fq 'cmp -s' "${wrapper}"
grep -Fq '/au250_xrt:ro' "${wrapper}"
grep -Fq ':/qwen-build' "${wrapper}"

grep -Fq '925e1179947ea0c0ebfb0032df18af3a729822be' "${builder}"
grep -Fq 'prepare_au250_qwen35_source.sh' "${builder}"
cargo_path_line="$(grep -nF 'export PATH="${CARGO_HOME}/bin:${PATH}"' "${builder}" | head -1 | cut -d: -f1)"
cargo_check_line="$(grep -nF 'command -v cargo' "${builder}" | head -1 | cut -d: -f1)"
test "${cargo_path_line}" -lt "${cargo_check_line}"
grep -Fq -- '-DGGML_CUDA=ON' "${builder}"
grep -Fq -- '-DGGML_CUDA_F16=ON' "${builder}"
grep -Fq -- '-DCMAKE_CUDA_ARCHITECTURES=120' "${builder}"
grep -Fq -- '-DLLAMA_BUILD_SERVER=ON' "${builder}"
grep -Fq -- '--target llama-server llama-cli' "${builder}"
grep -Fq -- '--features nvidia,embed_cudart,evaluation' "${builder}"
grep -Fq 'hetgpu_tq1_register_tensor_v1' "${builder}"
grep -Fq 'hetgpu_tq1_try_mul_mat_id_v1' "${builder}"
grep -Fq 'sha256sum' "${builder}"
test "$(grep -Fc -- '--ignore-submodules=all' "${builder}")" -ge 2
grep -Fq 'cuda_math_header_sha256' "${builder}"
grep -Fq '/qwen-build/manifest.json' "${builder}"

echo "PASS: static Qwen AU250 runtime workflow contract"
