#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
runner="${repo_root}/tools/au250_hybrid_run.sh"
builder="${repo_root}/tools/build_au250_kimi_runtime.sh"

bash -n "${runner}"
bash -n "${builder}"
rendered="$(${runner} --print-docker true)"
grep -Fq -- '--gpus all' <<<"${rendered}"
grep -Fq -- '-v /au250_xrt:/au250_xrt:ro' <<<"${rendered}"
grep -Fq -- '/usr/local/cuda-13.0:/usr/local/cuda-13.0:ro' <<<"${rendered}"
grep -Fq -- '/home/eabban/BitNet:/bitnet:ro' <<<"${rendered}"
grep -Fq -- '/root/models/kimi-k2.6-iq1_s/moonshotai_Kimi-K2.6-IQ1_S:/models/kimi:ro' <<<"${rendered}"
grep -Fq -- 'app215' <<<"${rendered}"
grep -Fq -- 'CMAKE_CUDA_ARCHITECTURES=120' "${builder}"
grep -Fq -- 'GGML_CUDA=ON' "${builder}"
grep -Fq -- 'LLAMA_ARG_N_GPU_LAYERS' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
! grep -Fq -- '-ngl 99' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'model_hash_cache' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- '--features nvidia,embed_cudart' "${builder}"
grep -Fq -- 'HETGPU_CUDART_SYMBOL_VERSION=13' "${builder}"
grep -Fq -- 'libhetgpu_cuda_shim.so' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'LD_PRELOAD="$cudart_shim:$libnvcuda"' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_CUDART_PRELAUNCH_NAMED_KERNEL=1' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_CUDART_PREFER_FATBIN_CUBIN_FOR_SASS=1' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_CUDART_COMPUTE_CAPABILITY=120' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_CUDART_FORWARD_REAL_DEVICE_INFO=1' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_CUDART_FORWARD_REAL_STREAMS=1' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_LIBGGML="$libggml"' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
! grep -Fq -- 'ln -s "$libnvcuda"' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'cuda13-rsqrt-noexcept.patch' "${builder}"
grep -Fq -- 'NVCC_PREPEND_FLAGS=-I/work/target/au250-cuda13-compat/include' "${builder}"
grep -Fq -- 'CMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-12' "${builder}"
grep -Fq -- 'CMAKE_CUDA_STANDARD=17' "${builder}"
grep -Fq -- 'CMAKE_CUDA_STANDARD_REQUIRED=ON' "${builder}"
grep -Fq -- 'cp -a "${cuda_include}/crt" "${compat_root}/"' "${builder}"
test -s "${repo_root}/tools/cuda13-rsqrt-noexcept.patch"
bash "${repo_root}/zluda/tests/test_prepare_au250_bitnet_source.sh"
grep -Fq -- 'prepare_au250_bitnet_source.sh' "${builder}"
grep -Fq -- 'au250-bitnet-source-au250-no-stream-k' "${builder}"
test -s "${repo_root}/tools/bitnet-disable-stream-k-for-au250.patch"
grep -Fq -- 'cudaError_t __cudaGetKernel(void** kernel, const void* f)' "${repo_root}/zluda/src/cudart_shim.c"
grep -Fq -- 'cuFuncSetAttribute(cu_func, attr, value)' "${repo_root}/zluda/src/cudart_shim.c"
grep -Fq -- 'cuFuncSetAttribute,' "${repo_root}/zluda/src/lib.rs"
grep -Fq -- 'nvidia_runtime_sys::cuFuncSetAttribute(hfunc.cuda_function, attrib, value)' "${repo_root}/zluda/src/impl/function.rs"
grep -Fq -- 'nvidia_runtime_sys::cuStreamSynchronize_ckpt(stream)' "${repo_root}/zluda/src/impl/function.rs"
grep -Fq -- 'uses stream-k tmp_fixup=' "${repo_root}/zluda/src/impl/function.rs"
grep -Fq -- 'HETGPU_CUDART_FORWARD_REAL_STREAMS' "${repo_root}/zluda/src/cudart_shim.c"
grep -Fq -- 'hetgpu_real_cudart_symbol("cudaStreamCreateWithFlags")' "${repo_root}/zluda/src/cudart_shim.c"
grep -Fq -- 'HETGPU_BITNET_CXL_KERNELS=mul_mat_q' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'HETGPU_XRT_ALLOW_NONFINITE_Q8_NATIVE=1' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
grep -Fq -- 'mul_mat_vec_q,attention' "${repo_root}/tools/run_kimi_k26_iq1s_au250_hybrid.sh"
