#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
wrapper="${repo_root}/tools/au250_qwen35_run.sh"
builder="${repo_root}/tools/build_au250_qwen35_runtime.sh"
cublas_shim="${repo_root}/zluda/src/cublas_shim.c"
runner="${repo_root}/tools/run_qwen35_tq1_au250_hybrid.sh"
evaluator="${repo_root}/tools/qwen35_au250_eval.py"
validator="${repo_root}/zluda/tests/validate_qwen35_tq1_au250_proof.py"
iq1s_runner="${repo_root}/tools/run_qwen35_iq1s_au250_hybrid.sh"
iq1s_validator="${repo_root}/zluda/tests/validate_qwen35_iq1s_au250_proof.py"
cuda13_launch_shim="${repo_root}/tools/qwen35_cuda13_launch_shim.c"
cuda13_launch_map="${repo_root}/tools/qwen35_cuda13_launch_shim.map"

test -x "${wrapper}"
test -x "${builder}"
test -x "${runner}"
test -x "${evaluator}"
test -x "${iq1s_runner}"
test -x "${iq1s_validator}"
bash -n "${wrapper}"
bash -n "${builder}"
bash -n "${runner}"
bash -n "${iq1s_runner}"
grep -Fq '#define _GNU_SOURCE' "${cublas_shim}"

grep -Fq 'AU250_QWEN_MODEL_ROOT:-/root/models/qwen35-tq1' "${wrapper}"
grep -Fq 'AU250_QWEN_LLAMA_ROOT:-/tmp/llama.cpp-qwen-context' "${wrapper}"
grep -Fq 'AU250_CUDA_ROOT:-/usr/local/cuda-13.0' "${wrapper}"
grep -Fq -- '--git-common-dir' "${wrapper}"
grep -Fq -- '-v "${git_common_dir}":"${git_common_dir}":ro' "${wrapper}"
grep -Fq '_au250_devflags' "${wrapper}"
grep -Fq '_au250_fpga_temp' "${wrapper}"
grep -Fq '/models/qwen:ro' "${wrapper}"
grep -Fq '/llama-pristine:ro' "${wrapper}"
grep -Fq '/usr/local/cuda-13.0:ro' "${wrapper}"
grep -Fq 'cuda-compat' "${wrapper}"
grep -Fq 'cuda_compat_math_header' "${wrapper}"
grep -Fq '/usr/local/cuda-13.0/targets/x86_64-linux/include/crt/math_functions.h:ro' "${wrapper}"
grep -Fq 'double rsqrt(double a) noexcept(true)' "${wrapper}"
grep -Fq 'float rsqrtf(float a) noexcept(true)' "${wrapper}"
grep -Fq 'cmp -s' "${wrapper}"
grep -Fq '/au250_xrt:ro' "${wrapper}"
grep -Fq ':/qwen-build' "${wrapper}"

grep -Fq '925e1179947ea0c0ebfb0032df18af3a729822be' "${builder}"
grep -Fq 'prepare_au250_qwen35_source.sh' "${builder}"
cargo_path_line="$(grep -nF 'export PATH="${CARGO_HOME}/bin:${PATH}"' "${builder}" | head -1 | cut -d: -f1)"
cargo_check_line="$(grep -nF 'command -v cargo' "${builder}" | head -1 | cut -d: -f1)"
test "${cargo_path_line}" -lt "${cargo_check_line}"
grep -Fq -- '-DGGML_CUDA=ON' "${builder}"
grep -Fq -- '-DGGML_CUDA_F16=ON' "${builder}"
grep -Fq -- '-DCMAKE_CUDA_ARCHITECTURES=120' "${builder}"
grep -Fq -- '-DLLAMA_BUILD_SERVER=ON' "${builder}"
grep -Fq -- '--target llama-server llama-cli' "${builder}"
grep -Fq -- '--features nvidia,embed_cudart,evaluation' "${builder}"
grep -Fq 'qwen35_cuda13_launch_shim.c' "${builder}"
grep -Fq 'qwen35_cuda13_launch_shim.map' "${builder}"
grep -Fq 'libqwen35_cuda13_launch_shim.so' "${builder}"
grep -Fq 'libcudart\.so\.13' "${builder}"
grep -Fq '__cudaRegisterFunction' "${builder}"
grep -Fq 'hetgpu_tq1_register_tensor_v1' "${builder}"
grep -Fq 'hetgpu_tq1_try_mul_mat_id_v1' "${builder}"
grep -Fq 'hetgpu_tq1_evaluate_raw_v1' "${builder}"
grep -Fq 'ldd -r' "${builder}"
grep -Fq 'tq1_upstream_reference.cpp' "${builder}"
grep -Fq 'tq1_upstream_reference' "${builder}"
grep -Fq 'sha256sum' "${builder}"
test "$(grep -Fc -- '--ignore-submodules=all' "${builder}")" -ge 2
grep -Fq 'cuda_math_header_sha256' "${builder}"
grep -Fq '/qwen-build/manifest.json' "${builder}"

grep -Fq -- '--ctx-size", "512"' "${evaluator}"
grep -Fq -- '--n-gpu-layers", "999"' "${evaluator}"
grep -Fq -- '--verbosity", "4"' "${evaluator}"
grep -Fq -- '--parallel", "1"' "${evaluator}"
grep -Fq '"n_predict": 32' "${evaluator}"
grep -Fq '"temperature": 0.0' "${evaluator}"
grep -Fq '"seed": 42' "${evaluator}"
grep -Fq '"cache_prompt": False' "${evaluator}"
grep -Fq 'MEASUREMENTS = 5' "${evaluator}"
grep -Fq 'WARMUPS = 1' "${evaluator}"
grep -Fq 'Reply with exactly OK and no other text.' "${evaluator}"
grep -Fq 'semantic' "${evaluator}"
grep -Fq 'sha256' "${evaluator}"
test "$(grep -Fc '/qwen-build/llama-build/bin/llama-server' "${runner}")" -eq 1
grep -Fq 'HETGPU_QWEN_TQ1_XRT=0' "${runner}"
grep -Fq 'HETGPU_QWEN_TQ1_XRT=1' "${runner}"
grep -Fq 'HETGPU_QWEN_TQ1_STRICT=1' "${runner}"
grep -Fq 'run_au250_xrt_tq1.sh' "${runner}"
last_effective_command="$(grep -Ev '^\s*(#|$|echo |printf )' "${runner}" | tail -1)"
test "${last_effective_command}" = 'python3 "${validator}" "${proof_dir}" | tee "${proof_dir}/summary.json"'

grep -Fq 'qwen35_gguf_audit.py' "${iq1s_runner}"
grep -Fq 'qwen35-iq1s-route-manifest.json' "${iq1s_runner}"
test "$(grep -Fc 'HETGPU_QWEN_TQ1_XRT=0' "${iq1s_runner}")" -eq 2
grep -Fq 'HETGPU_TMATMUL_BACKEND=xrt' "${iq1s_runner}"
grep -Fq 'HETGPU_BITNET_DISAGGREGATE=1' "${iq1s_runner}"
grep -Fq 'HETGPU_BITNET_DISAGG_STRICT=1' "${iq1s_runner}"
grep -Fq 'HETGPU_TMATMUL_HARDWARE_MATMUL=1' "${iq1s_runner}"
grep -Fq 'HETGPU_QWEN35_CUDA_BUFFER_MAX_MIB=49152' "${iq1s_runner}"
grep -Fq 'HETGPU_CUDART_PRELAUNCH_NAMED_KERNEL=1' "${iq1s_runner}"
grep -Fq 'libqwen35_cuda13_launch_shim.so' "${iq1s_runner}"
grep -Fq '"${cuda13_launch_shim}:${libnvcuda}"' "${iq1s_runner}"
test -f "${cuda13_launch_shim}"
test -f "${cuda13_launch_map}"
grep -Fq 'run_au250_xrt_tq1.sh' "${iq1s_runner}"
grep -Fq 'validate_qwen35_iq1s_au250_proof.py' "${iq1s_runner}"
iq1s_last_effective_command="$(grep -Ev '^\s*(#|$|echo |printf )' "${iq1s_runner}" | tail -1)"
test "${iq1s_last_effective_command}" = 'python3 "${iq1s_validator}" "${proof_dir}" | tee "${proof_dir}/summary.json"'

echo "PASS: static Qwen AU250 runtime workflow contract"
