obj-m += hetgpu_sifive_mbox.o
obj-m += hetgpu_sifive_mbox_live.o
obj-m += hetgpu_sifive_live.o
obj-m += hetgpu_sifive_mbox_full.o
obj-m += hetgpu_sifive_mbox_ddr.o
obj-m += hetgpu_sifive_mbox_ddr_coh.o
